<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>About</name>
   <tag></tag>
   <elementGuidId>b1212dc5-242d-4c6f-a3f3-5887bce396da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div//span[text()='About']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div//span[text()='About']</value>
      <webElementGuid>e81867de-c1b4-452d-aea2-1b3620ed03c9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
