<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LoginBtn</name>
   <tag></tag>
   <elementGuidId>d54d5a67-8a61-4890-9748-6225d2895569</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[id=&quot;login-btn&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[id=&quot;login-btn&quot;]</value>
      <webElementGuid>b1573d70-0a9c-466c-bd8d-2c9c842fd874</webElementGuid>
   </webElementProperties>
</WebElementEntity>
