<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Solutions</name>
   <tag></tag>
   <elementGuidId>21839aec-7549-46d6-ba23-41ba4a91797f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div//span[text()='Solutions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div//span[text()='Solutions']</value>
      <webElementGuid>b7dd4b98-e07e-46e8-8fe8-d09dee8d4158</webElementGuid>
   </webElementProperties>
</WebElementEntity>
