<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LoginBtn</name>
   <tag></tag>
   <elementGuidId>fa9b7c07-bc74-44f6-8290-a2b84e9c4f91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//button[@type=&quot;submit&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//button[@type=&quot;submit&quot;])[1]</value>
      <webElementGuid>f8d43f16-c9a1-48a9-993e-17dee496f39c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
